### ISSUE TITLE
Schema validation is getting failed for larger schema inputs

### ISSUE THREAD

**Issue by LakshmiMekala** [project-flogo/graphql#13]
**Current behavior (how does the issue manifest):**
Attached test.log file
**Expected behavior:**
flogo app should work without schema errors, tried with different schemas and attached schema files

**Minimal steps to reproduce the problem (not required if feature enhancement):**
Create and build flogo app with example.json
Run the app
**Please tell us about your environment (Operating system, docker version, browser & web ui version, etc):**
Linux
**Flogo version (CLI & contrib/lib. If unknown, leave empty or state unknown):** 0.X.X
flogo latest version

**Additional information you deem important (e.g. issue happens only occasionally):**

[example.zip](https://github.com/project-flogo/graphql/files/3372590/example.zip)

**Comment by cpramodroy** [comment]
@LakshmiMekala The current graphql implementation(in project-flogo) does not support having comments in the schema. This is because the entire schema is converted to a single line before being serialized. So once a '#' is encountered, the parse api considers everything after it until a 'new line' is reached as part of the comment. So in our case, the rest of the schema is considered as a comment which is not the right behavior.  There is currently an open ticket in project-flogo/flogo-web to allow the text box field to input multi-line text. See [here.](https://github.com/project-flogo/flogo-web/issues/1096)

So by removing the lines with comments (The lines that start with '#'), I was able to create and run an application using schema.graphql.

Comments are however not a problem when using the feature in Flogo Enterprise.
